name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Check Go formatting
      run: |
        if ! gofmt -l . | grep -q .; then
          echo "All Go files are properly formatted"
        else
          echo "The following Go files are not properly formatted:" && gofmt -l .
          exit 1
        fi

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.64.2/golangci-lint-1.64.2-linux-amd64.tar.gz | tar -xz -C /tmp
        sudo mv /tmp/golangci-lint-1.64.2-linux-amd64/golangci-lint /usr/local/bin

    - name: Run linter
      run: golangci-lint run --timeout 5m
